import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createCourse, uploadVideo } from '../../api/courseApi.js';
import { useAuth } from '../../hooks/useAuth.js';
import { Loader } from '../../components/Loader';
import { Save, Plus, Trash2, CheckCircle, Copy } from 'lucide-react';
import './CreateCourse.css';

export const CreateCourse = () => {
  const { token, user } = useAuth();
  const navigate = useNavigate();

  const [title, setTitle]           = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory]     = useState('Development');
  const [level, setLevel]           = useState('Beginner');
  const [price, setPrice]           = useState(0);
  const [imageFile, setImageFile]   = useState(null);

  const [modules, setModules] = useState([
    { title: 'Introduction', type: 'video', content: '', durationMinutes: 10 }
  ]);

  const [loading, setLoading]               = useState(false);
  const [error, setError]                   = useState('');
  const [createdCourse, setCreatedCourse]   = useState(null); // holds the newly created course
  const [videoUploading, setVideoUploading] = useState({});
  const [copied, setCopied]                 = useState(false);

  const handleAddLesson = () => {
    setModules([
      ...modules,
      { title: `Module ${modules.length + 1}`, type: 'video', content: '', durationMinutes: 10 }
    ]);
  };

  const handleRemoveLesson = (idx) => {
    setModules(modules.filter((_, i) => i !== idx));
  };

  const handleLessonChange = (idx, field, val) => {
    const updated = [...modules];
    updated[idx][field] = val;
    setModules(updated);
  };

  const handleVideoUpload = async (idx, file) => {
    if (!file) return;
    setVideoUploading(prev => ({ ...prev, [idx]: true }));
    try {
      const res = await uploadVideo(file, token);
      handleLessonChange(idx, 'content', res.url);
    } catch (err) {
      setError(`Video upload failed for module ${idx + 1}: ${err.message}`);
    } finally {
      setVideoUploading(prev => ({ ...prev, [idx]: false }));
    }
  };

  const handleCopyId = () => {
    if (!createdCourse?._id) return;
    navigator.clipboard.writeText(createdCourse._id);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!user.isApproved) {
      setError('Cannot publish courses: Your account is pending administrator approval.');
      return;
    }
    setError('');
    setLoading(true);

    const formData = new FormData();
    formData.append('title', title);
    formData.append('description', description);
    formData.append('category', category);
    formData.append('level', level);
    formData.append('price', price);
    formData.append('modules', JSON.stringify(modules));
    if (imageFile) formData.append('coverImage', imageFile);

    try {
      const res = await createCourse(formData, token);
      // Show the auto-generated course ID to the instructor
      setCreatedCourse(res.course);
    } catch (err) {
      setError(err.message || 'Failed to create course. Please review all fields.');
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <Loader />;

  // ── Success state: course created, show ID banner ─────────────────
  if (createdCourse) {
    return (
      <div className="page-wrapper create-course-container">
        <div className="course-created-banner">
          <CheckCircle size={48} color="#10b981" style={{ marginBottom: '1rem' }} />
          <h2 className="course-created-title">Course Published Successfully!</h2>
          <p className="course-created-sub">
            Your course <strong>"{createdCourse.title}"</strong> is now live in the catalog.
          </p>

          {/* Auto-generated Course ID */}
          <div className="course-id-box">
            <span className="course-id-label">Auto-Generated Course ID</span>
            <div className="course-id-row">
              <code className="course-id-value">{createdCourse._id}</code>
              <button
                className="btn btn-secondary course-id-copy-btn"
                onClick={handleCopyId}
                title="Copy to clipboard"
              >
                <Copy size={14} />
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
            <p className="course-id-hint">
              This unique MongoDB ObjectId was automatically generated by the server.
              Use it for direct API calls or to reference this course in enrollments.
            </p>
          </div>

          <div className="course-created-meta">
            <div className="course-created-meta-item">
              <span className="course-meta-label">Category</span>
              <span className="course-meta-val">{createdCourse.category}</span>
            </div>
            <div className="course-created-meta-item">
              <span className="course-meta-label">Level</span>
              <span className="course-meta-val">{createdCourse.level}</span>
            </div>
            <div className="course-created-meta-item">
              <span className="course-meta-label">Price</span>
              <span className="course-meta-val">{createdCourse.price === 0 ? 'Free' : `₹${createdCourse.price}`}</span>
            </div>
            <div className="course-created-meta-item">
              <span className="course-meta-label">Modules</span>
              <span className="course-meta-val">{createdCourse.modules?.length || 0}</span>
            </div>
          </div>

          <div className="course-created-actions">
            <button className="btn btn-primary" onClick={() => navigate('/instructor/my-courses')}>
              View My Courses
            </button>
            <button
              className="btn btn-secondary"
              onClick={() => {
                setCreatedCourse(null);
                setTitle(''); setDescription(''); setCategory('Development');
                setLevel('Beginner'); setPrice(0); setImageFile(null);
                setModules([{ title: 'Introduction', type: 'video', content: '', durationMinutes: 10 }]);
              }}
            >
              Create Another Course
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Create form ───────────────────────────────────────────────────
  return (
    <div className="page-wrapper create-course-container">
      <div className="create-course-header">
        <h1 className="create-course-title">Author New Course</h1>
        <p className="create-course-sub">
          Fill in course details and build your syllabus. A unique Course ID will be auto-generated on save.
        </p>
      </div>

      {error && <div className="create-course-error-alert">{error}</div>}

      <form onSubmit={handleSubmit} className="create-course-layout">

        {/* ── Left: Course Info ── */}
        <div className="glass-card create-course-left-card">
          <h3 className="create-course-card-header">1. Course Information</h3>

          <div className="form-group">
            <label className="form-label">Course Title</label>
            <input
              type="text"
              className="form-input"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Master React in 30 Days"
              required
            />
          </div>

          {/* ID placeholder — shown before creation */}
          <div className="form-group">
            <label className="form-label">Course ID</label>
            <div className="course-id-pending">
              <span className="course-id-pending-text">⚙ Auto-generated by server on save</span>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Description</label>
            <textarea
              className="form-textarea create-course-textarea"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Provide a detailed overview of what students will learn..."
              rows={5}
              required
            />
          </div>

          <div className="create-course-split-row">
            <div className="form-group" style={{ flex: 1 }}>
              <label className="form-label">Category</label>
              <select className="form-select" value={category} onChange={(e) => setCategory(e.target.value)}>
                <option value="Development">Development</option>
                <option value="Design">Design</option>
                <option value="Business">Business</option>
                <option value="Marketing">Marketing</option>
              </select>
            </div>

            <div className="form-group" style={{ flex: 1 }}>
              <label className="form-label">Level</label>
              <select className="form-select" value={level} onChange={(e) => setLevel(e.target.value)}>
                <option value="Beginner">Beginner</option>
                <option value="Intermediate">Intermediate</option>
                <option value="Advanced">Advanced</option>
              </select>
            </div>
          </div>

          <div className="create-course-split-row">
            <div className="form-group" style={{ flex: 1 }}>
              <label className="form-label">Price (₹ INR)</label>
              <input
                type="number"
                className="form-input"
                value={price}
                onChange={(e) => setPrice(Math.max(0, Number(e.target.value)))}
                min={0}
                required
              />
            </div>

            <div className="form-group" style={{ flex: 1 }}>
              <label className="form-label">Cover Image</label>
              <input
                type="file"
                className="form-input create-course-file-input"
                onChange={(e) => setImageFile(e.target.files[0])}
                accept="image/*"
              />
              {imageFile && (
                <p style={{ fontSize: '0.75rem', color: '#10b981', marginTop: '0.3rem' }}>
                  ✓ {imageFile.name}
                </p>
              )}
            </div>
          </div>
        </div>

        {/* ── Right: Syllabus ── */}
        <div className="create-course-right-column">
          <div className="glass-card create-course-right-card">
            <div className="create-course-right-card-header">
              <h3 className="create-course-card-header">2. Syllabus Modules</h3>
              <button type="button" className="btn btn-secondary create-course-add-btn" onClick={handleAddLesson}>
                <Plus size={16} /> Add Module
              </button>
            </div>

            <div className="create-course-lessons-list">
              {modules.length === 0 ? (
                <p className="create-course-empty-lessons">No modules yet. Add at least one module.</p>
              ) : (
                modules.map((lesson, idx) => (
                  <div key={idx} className="create-course-lesson-item">
                    <div className="create-course-lesson-header-row">
                      <span className="create-course-lesson-index">Module #{idx + 1}</span>
                      <button type="button" className="create-course-delete-btn" onClick={() => handleRemoveLesson(idx)}>
                        <Trash2 size={16} color="#ef4444" />
                      </button>
                    </div>

                    <div className="form-group" style={{ marginBottom: '0.75rem' }}>
                      <input
                        type="text"
                        className="form-input create-course-lesson-input"
                        value={lesson.title}
                        onChange={(e) => handleLessonChange(idx, 'title', e.target.value)}
                        placeholder="Module Title"
                        required
                      />
                    </div>

                    <div className="create-course-lesson-split">
                      <select
                        className="form-select create-course-lesson-input"
                        style={{ flex: 1 }}
                        value={lesson.type}
                        onChange={(e) => handleLessonChange(idx, 'type', e.target.value)}
                      >
                        <option value="video">Video Lecture</option>
                        <option value="document">Text Document</option>
                      </select>

                      <input
                        type="number"
                        className="form-input create-course-lesson-input"
                        style={{ width: '90px' }}
                        value={lesson.durationMinutes}
                        onChange={(e) => handleLessonChange(idx, 'durationMinutes', Number(e.target.value))}
                        placeholder="Min"
                        title="Duration in minutes"
                      />
                    </div>

                    {lesson.type === 'video' ? (
                      <div style={{ marginTop: '0.75rem' }}>
                        <label className="form-label" style={{ fontSize: '0.8rem', marginBottom: '0.4rem' }}>
                          Upload Video (Cloudinary)
                        </label>
                        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
                          <input
                            type="file"
                            accept="video/*"
                            className="form-input create-course-file-input"
                            style={{ flex: 1 }}
                            disabled={videoUploading[idx]}
                            onChange={(e) => handleVideoUpload(idx, e.target.files[0])}
                          />
                          {videoUploading[idx] && (
                            <span style={{ fontSize: '0.75rem', color: '#6366f1' }}>Uploading…</span>
                          )}
                        </div>
                        <label className="form-label" style={{ fontSize: '0.8rem', marginBottom: '0.4rem' }}>
                          Or paste video URL
                        </label>
                        <input
                          type="text"
                          className="form-input create-course-lesson-input"
                          value={lesson.content}
                          onChange={(e) => handleLessonChange(idx, 'content', e.target.value)}
                          placeholder="https://youtube.com/… or Cloudinary URL"
                        />
                        {lesson.content && (
                          <p style={{ fontSize: '0.72rem', color: '#10b981', marginTop: '0.3rem' }}>✓ Video URL set</p>
                        )}
                      </div>
                    ) : (
                      <div className="form-group" style={{ marginTop: '0.75rem', marginBottom: 0 }}>
                        <input
                          type="text"
                          className="form-input create-course-lesson-input"
                          value={lesson.content}
                          onChange={(e) => handleLessonChange(idx, 'content', e.target.value)}
                          placeholder="Document content or description"
                          required
                        />
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>

            <button type="submit" className="btn btn-primary create-course-save-btn">
              <Save size={18} />
              <span>Save & Get Course ID</span>
            </button>
          </div>
        </div>
      </form>
    </div>
  );
};

export default CreateCourse;
