require('dotenv').config();

module.exports = {
  PORT: process.env.PORT || '5000',
  
  JWT_SECRET: process.env.JWT_SECRET,

  CLIENT_ORIGIN: process.env.CLIENT_ORIGIN,

  MONGO_URI: process.env.MONGO_URI,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,

  ADMIN_REGISTER_SECRET: process.env.ADMIN_REGISTER_SECRET,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,

  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,

  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,

  SENDGRID_FROM_EMAIL: process.env.SENDGRID_FROM_EMAIL
}; 
